// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADrQGqQpZ7S1nSPW1FNbOW69sCzmyOxhk',
    appId: '1:948537560038:web:126105f514db08a2272427',
    messagingSenderId: '948537560038',
    projectId: 'sawari-6e541',
    authDomain: 'sawari-6e541.firebaseapp.com',
    storageBucket: 'sawari-6e541.firebasestorage.app',
    measurementId: 'G-VFHFT3JR6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV74U6ApRD4r53ERhcBgScIbMMqGDdUxw',
    appId: '1:948537560038:android:1d49eaee4dd68eda272427',
    messagingSenderId: '948537560038',
    projectId: 'sawari-6e541',
    storageBucket: 'sawari-6e541.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC-_k3Q9NgJSSPkW-_M7w-_6V6-pkjIPE',
    appId: '1:948537560038:ios:4d1bcd33ac64de5b272427',
    messagingSenderId: '948537560038',
    projectId: 'sawari-6e541',
    storageBucket: 'sawari-6e541.firebasestorage.app',
    iosBundleId: 'com.muhammadabdullah.sawari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC-_k3Q9NgJSSPkW-_M7w-_6V6-pkjIPE',
    appId: '1:948537560038:ios:4d1bcd33ac64de5b272427',
    messagingSenderId: '948537560038',
    projectId: 'sawari-6e541',
    storageBucket: 'sawari-6e541.firebasestorage.app',
    iosBundleId: 'com.muhammadabdullah.sawari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADrQGqQpZ7S1nSPW1FNbOW69sCzmyOxhk',
    appId: '1:948537560038:web:2e920f3427bb84c2272427',
    messagingSenderId: '948537560038',
    projectId: 'sawari-6e541',
    authDomain: 'sawari-6e541.firebaseapp.com',
    storageBucket: 'sawari-6e541.firebasestorage.app',
    measurementId: 'G-NH3K84WXY6',
  );
}
